language: r
cache: packages
sudo: true
apt_packages: libnetcdf-dev
r: bioc-devel
  
    
after_success:
  - Rscript -e 'covr::codecov()'

# print timings (of examples) and sysinfo
after_script:
  - dump_logs_by_extension "timings"
  - dump_sysinfo

notifications:
  email:
    on_failure: lg390@cam.ac.uk

